"""initial

Revision ID: 36bece7dafec
Revises: 
Create Date: 2025-11-11 22:09:30.851659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bece7dafec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nim', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('nim')

    # ### end Alembic commands ###
